# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04f8b4d0484432e79c923b90b1bc05bf88f70fefad77ac187a97a21d3227fc35853c1422a4c73aded42e54db0596aa3da4540fde9d6d99497f4bf6c2bced2ca7

test:
  secret_key_base: f7dff0db17938bdde86baffca2dd8965cbb537c72679e05220eae15d8a914c4ec792c474d60563f736fc79260bb458e4c3840480394eae20c07b1ff57118d74d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
